# OBJS ARE THE SOURCE FILES
OBJS := main.cpp chip8.cpp 

# CC IS THE COMPILER
CC := g++

# FLAGS
FLAGS := -Wall -Wextra -pedantic

# LIBS ARE THE LIBRARIES TO LINK AGAINST
LIBS := -lSDL2

# TARGET EXECUTABLE
TARGET := chip8

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(FLAGS) $(LINKER_FLAGS) $(LIBS) -o $(TARGET)

clean: 
	rm $(TARGET)


